### ISSUE TITLE
JSON Schema examples

### ISSUE THREAD

**Issue by cp-weiland** [DiSSCo/openDS#17]
Hi, 
I pulled the DS and the JSON Schemas out and did some minor corrections to pass validation:
https://github.com/cp-weiland/openDS-schema
Schema corrections are in the [git log](https://github.com/cp-weiland/openDS-schema/commit/ac6088fc1ca982ac899314de3ccc925fee0ad6aa#diff-4afcee55bfb26ccde4ecfc4673f857e7336cab94e6abf43d2ab6a5c6df233595).

**Comment by wouteraddink** [comment]
I think the institution array values need to be defined as properties, otherwise you do not know what they are. So instead of "type" with "items" as "array" (like "institution": [  "MNHN", "https://ror.org/03wkt5x30" ], it should have something to define "institution":[ "institutionCode"="MNHN", "RORID'="https://ror.org/03wkt5x30" ]

**Comment by wouteraddink** [comment]
physicalSpecimenId does not take into account curated objects that are not physical specimens/material samples, like a digital image or sound recording. We could change it to curatedObjectID with as definition: identifier for the curated tangible thing (visible, touchable, audible or smellable), for example a sample of some material, a sound recording or a digital image.

**Comment by sharifX** [comment]
we now have a schema repo (https://schemas.dissco.tech/). In the [github data model](https://github.com/DiSSCo/openDS/tree/master/data-model) folder we have provided some recent examples.
