### ISSUE TITLE
terms for media content

### ISSUE THREAD

**Issue by CecSve** [DiSSCo/openDS#194]
### Suggestion

I could not find any information from the [terms list](https://dev.terms.dissco.tech/digital-specimen-terms) or in the media schema so I will ask here instead. Are you considering adding terms to specify what the content of an image is? For example, some collections digitize a specimen by including images of the specimen and the labels separately. It could be useful for a user to be able to filter on labels or images specifically.

**Comment by samleeflang** [comment]
Hi Cecilie, thanks for your feedback!
I am looking into the `ods:DigitalMedia` and see if we can align it better with the [Audiovisual Core](https://ac.tdwg.org/) and the [DWCA extension Audubon Media Description](https://rs.gbif.org/extension/ac/audubon_2020_10_06.xml). 
However, when I go through the terms, I don't see any term covering your question.
Terms such as `ac:subtype` or especially `ac:subjectPart` feel appropriate, but the Controlled Vocabulary attached to these two terms do not contain a value for indicating if this is an image of a label or a specimen. 
I rather than solving this at DiSSCo level, we would like to solve this at the TDWG level.
Would you be open to discuss this question in the Audiovisual Core Maintenance Group? 
I might also just have missed the appropriate term, but hopefully they can help with that as well.

**Comment by samleeflang** [comment]
Excellent, yes, that looks to exactly match our discussion. I DiSSCo will add this AC term in a later iteration after the AC Maintenance Group has accepted it. Closing this ticket, but feel free to reopen when there are additional questions/comments.
